// Package kbgo is auto-generated by GoFrame CLI tool.
// This file is auto-generated and should NOT be edited.
package kbgo

import (
	"context"

	"github.com/Malowking/kbgo/api/kbgo/v1"
)

//go:generate gf gen ctrl -c -g -t kbgo -a
type IKbgoV1 interface {
	// Chat related interfaces
	Chat(ctx context.Context, req *v1.ChatReq) (res *v1.ChatRes, err error)

	// Document related interfaces
	DocumentsList(ctx context.Context, req *v1.DocumentsListReq) (res *v1.DocumentsListRes, err error)
	DocumentsDelete(ctx context.Context, req *v1.DocumentsDeleteReq) (res *v1.DocumentsDeleteRes, err error)

	// Indexing related interfaces
	IndexDocuments(ctx context.Context, req *v1.IndexDocumentsReq) (res *v1.IndexDocumentsRes, err error)

	// Chunk related interfaces
	ChunksList(ctx context.Context, req *v1.ChunksListReq) (res *v1.ChunksListRes, err error)
	ChunkDelete(ctx context.Context, req *v1.ChunkDeleteReq) (res *v1.ChunkDeleteRes, err error)
	UpdateChunk(ctx context.Context, req *v1.UpdateChunkReq) (res *v1.UpdateChunkRes, err error)

	// Knowledge base related interfaces
	KBGetList(ctx context.Context, req *v1.KBGetListReq) (res *v1.KBGetListRes, err error)
	KBCreate(ctx context.Context, req *v1.KBCreateReq) (res *v1.KBCreateRes, err error)
	KBDelete(ctx context.Context, req *v1.KBDeleteReq) (res *v1.KBDeleteRes, err error)

	// Upload related interfaces
	UploadFile(ctx context.Context, req *v1.UploadFileReq) (res *v1.UploadFileRes, err error)

	// Retriever related interfaces
	Retriever(ctx context.Context, req *v1.RetrieverReq) (res *v1.RetrieverRes, err error)

	// MCP related interfaces
	MCPRegistryCreate(ctx context.Context, req *v1.MCPRegistryCreateReq) (res *v1.MCPRegistryCreateRes, err error)
	MCPRegistryUpdate(ctx context.Context, req *v1.MCPRegistryUpdateReq) (res *v1.MCPRegistryUpdateRes, err error)
	MCPRegistryDelete(ctx context.Context, req *v1.MCPRegistryDeleteReq) (res *v1.MCPRegistryDeleteRes, err error)
	MCPRegistryGetOne(ctx context.Context, req *v1.MCPRegistryGetOneReq) (res *v1.MCPRegistryGetOneRes, err error)
	MCPRegistryGetList(ctx context.Context, req *v1.MCPRegistryGetListReq) (res *v1.MCPRegistryGetListRes, err error)

	// Model management interfaces
	ReloadModels(ctx context.Context, req *v1.ReloadModelsReq) (res *v1.ReloadModelsRes, err error)
	ListModels(ctx context.Context, req *v1.ListModelsReq) (res *v1.ListModelsRes, err error)
	GetModel(ctx context.Context, req *v1.GetModelReq) (res *v1.GetModelRes, err error)
	ChatCompletion(ctx context.Context, req *v1.ChatCompletionReq) (res *v1.ChatCompletionRes, err error)
	EmbeddingCompletion(ctx context.Context, req *v1.EmbeddingReq) (res *v1.EmbeddingRes, err error)
}
