// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package kbgo

import (
	"github.com/Malowking/kbgo/api/kbgo"
)

type ControllerV1 struct{}

func NewV1() kbgo.IKbgoV1 {
	return &ControllerV1{}
}
